apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nginxhello
  name: single-default-backend-ingress
  namespace: flux-test
  annotations:
    fluxcd.io/ignore: "true"
#spec:
#  backend:
#    serviceName: nginxhello
#    servicePort: 80
spec:
  rules:
  - host: nginxhello.local
    http:
      paths:
      - backend:
          service:
            name: nginxhello
            port:
              number: 80
        path: /
        pathType: Prefix

